/* CREACION DE LA BASE DE DE DATOS PARA EL PROYECTO hetacombe*/
CREATE DATABASE IF NOT EXISTS `apiMusic` CHARACTER SET = utf8mb4;
USE `apiMusic`;

CREATE TABLE `users`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `lastname` VARCHAR(100) NOT NULL,
    `email` VARCHAR(50) UNIQUE NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `role` ENUM('user', 'admin') DEFAULT 'user',
    `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `user_state` INT(2) NOT NULL DEFAULT 1 COMMENT '0=Inactivo 1=Activo',
    PRIMARY KEY(`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `songs`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `album` VARCHAR(100) NOT NULL,
    `cover` VARCHAR(50) NOT NULL,
    `artist_name` VARCHAR(100) NOT NULL,
    `artist_nickname` VARCHAR(100) NOT NULL,
    `artist_nationality` VARCHAR(50) NOT NULL,
    `duration_start` INT(5) NOT NULL,
    `duration_end` INT(5) NOT NULL,
    `media_id` INT(5) NOT NULL,
    `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `storages`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `url` VARCHAR(100) NOT NULL,
    `filename` VARCHAR(100) NOT NULL,
    `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;